language: ruby
bundler_args: --without guard
rvm:
  - "2.0"
  - "2.1"
  - "2.2"
  - ruby-head
script: "bundle exec rspec"
addons:
  code_climate:
    repo_token: 4ce664811485b705e1c44aa00ff41f207347874b2e840e38f27880f8ebaf96e5
branches:
  only: master
notifications:
  email: false
